### ISSUE TITLE
Loading game freezes my pc completely

### ISSUE THREAD

**Issue by SouthernPixelYT** [FoundationGames/Animatica#17]
I have tried both with and without using this mod and when i do load the game with this mod it either freezes my pc up completely making me forcefully shut it down (its already done it 3 times) or it makes the game stop responding while it loading into the game and even if it loads it makes the game or switching resourcepacks super laggy. Ive tested this with me just running minecraft as well as having 6GB of ram allocated to minecraft and i still get the same results. Ive tested this for 1.17.1 fabric so idk if it does the same thing for 1.18.1 fabric

Here is a list of all my mods if that helps (excluding Animatica)... https://imgur.com/a/AsvkWbx

**Comment by FoundationGames** [comment]
If you are stacking animated resource packs on top of each other that might be the issue, it's generating too many animations

**Comment by SouthernPixelYT** [comment]
im not stacking any animated resourcepacks. Im only using 1. ive even tried using none and the mod still causes this. Here are my mostly used packs https://imgur.com/a/o529eoX

**Comment by FoundationGames** [comment]
There is a config option in the `.minecraft/config/animatica.properties` file to set the max number of animation frames, set it to 500 or something like that (it should fix the issue, but might break animations)

It would help if you could find specifically which pack causes the crash

**Comment by SouthernPixelYT** [comment]
How do i edit that properties file? I click edit with notepad++ but nothing shows in it ive even tried turning it into a json or a txt file first and still nothing shows up.

**Comment by SouthernPixelYT** [comment]
I have tried loading the game with the mod but without ANY resourcepacks loaded and it still happens

**Comment by SouthernPixelYT** [comment]
Hello?

**Comment by FoundationGames** [comment]
This mod shouldn't be doing anything if you have no resource packs loaded, I can't reproduce the bug on my end that way

**Comment by SouthernPixelYT** [comment]
Can you reproduce it if you try using the mods im using?

**Comment by FoundationGames** [comment]
It would help more if you could tell me if the issue continues without any of the other mods (if so, I can try and find which one)

**Comment by SouthernPixelYT** [comment]
Yes, it works without any other mods. Doesnt really make sense to me though because they work all fine together but without this mod :/
I really want to use this mod but i cant use it if idk whats causing it.

**Comment by SouthernPixelYT** [comment]
Any luck figuring out whats causing it?

**Comment by SouthernPixelYT** [comment]
Um, hello?

**Comment by SouthernPixelYT** [comment]
I have tried editing the animatica.properties but nothing is in it at all when i open it

**Comment by EGOIST1372** [comment]
@FoundationGames I have same issue in 1.19.3 and when it's loading the game with mojang logo it stops responding and force closes and telling me to give the game more ram to fix this issue but I already gave it 6GB
